### ISSUE TITLE
front end auth

### ISSUE THREAD

**Issue by ngLawrence2** [ngLawrence2/Yelp-Clone#2]
- [X] Backend: DB, model, controller, views
- [X] Redux Loop: ajax, actions, reducer
- [X] Presentational Components
- [X] Styling
 - [X] When errors are displayed, the input boxes should not move
- [X] Smooth, bug free navigation
 - [X] Login errors clears when switching from login form to sign up form (and vice-versa)
 - [X] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
 - [X] Errors should display for both `/signup` and`/login`.
 - [X] Errors should clear when moving between `/signup` and `/login`.
- [X] Adequate and appropriate seeds
 - [X] Demo Login Works

**Comment by xnanodax** [comment]
Consider more spacing between links on the nav bar!
Yelp:
![screen shot 2018-08-15 at 10 05 27 am](https://user-images.githubusercontent.com/20424731/44161630-c795cf80-a072-11e8-90dd-ca4ea508fd7e.png)
Current Yelp-Clone-415:
![screen shot 2018-08-15 at 10 05 29 am](https://user-images.githubusercontent.com/20424731/44161632-c8c6fc80-a072-11e8-9637-b9dffa651671.png)
